blank_issues_enabled: false
contact_links:
  - name: 💬 Question or idea
    url: https://github.com/jaredcat/plushonscreen/discussions
    about: For anything that isn't a specific sighting submission.
